djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.views import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users', include(('users.urls', 'users'), namespace='users')),
    path('', include(('learning_log.urls', 'learning_log'), namespace='learning_log')),
    path('favicon.ico', serve, {'path': 'static/favicon.ico'}),


]

learning_log/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [url(r'^$', views.index, name='index'),
               url(r'^topics/$', views.topics, name='topics'),
               url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
               url(r'^new_topic/$', views.new_topic, name='new_topic'),
               url(r'^new_entry/(?P<topic_id>\d+)$', views.new_entry, name='new_entry'),
               url(r'^edit_entery/(?P<entry_id>\d)+/$', views.edit_entry, name='edit_entry'),
               ]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from . import views

urlpatterns = [url('^login/$', LoginView.as_view(template_name='users/login.html'), name='login'),
               url('^logout/$', views.logout_view, name='logout'),
               url('^register/$', views.register, name='register'),

               ]

learning_log/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    text = models.CharField(max_length=200)
    createDate = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    isPublic = models.BooleanField(default=True)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    createDate = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    isPublic = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) > 50:
            return self.text[:50] + '...'
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_log/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text', 'isPublic']
        labels = {'text': '', 'isPublic': '设为公开，其他用户登陆后可以看到这个话题'}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text', 'isPublic']
        labels = {'text': '', 'isPublic': '设为公开，其他用户登陆后可以看到这个内容'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_log/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect, Http404
from .models import Topic
from .forms import TopicForm, EntryForm, Entry
from django.contrib.auth.decorators import login_required
from django.db.models import Q


def index(request):
    return render(request, 'learning_log/index.html')


@login_required
def topics(request):
    get_topics = Topic.objects.filter(Q(owner=request.user) | Q(isPublic=True)).order_by('createDate')
    context = {'topics': get_topics}
    return render(request, 'learning_log/topics.html', context)


@login_required
def topic(request, topic_id):
    get_topic = Topic.objects.get(id=topic_id)
    if get_topic.owner != request.user and not get_topic.isPublic:
        raise Http404
    entries = get_topic.entry_set.filter(Q(owner=request.user) | Q(isPublic=True)).order_by('-createDate')
    context = {'topic': get_topic, 'entries': entries}
    return render(request, 'learning_log/topic.html', context)


@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            form.instance.owner = request.user
            form.save()
            return HttpResponseRedirect(reverse('learning_log:topics'))
    context = {'form': form}
    return render(request, 'learning_log/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    topic1 = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry1 = form.save(commit=False)
            new_entry1.owner = request.user
            new_entry1.topic = topic1
            new_entry1.save()
            return HttpResponseRedirect(reverse('learning_log:topic', args=[topic_id]))
    context = {'topic': topic1, 'form': form}
    return render(request, 'learning_log/new_entry.html', context)


@login_required()
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic1 = entry.topic
    if topic1.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_log:topic', args=[topic1.id]))
    context = {'entry': entry, 'topic': topic1, 'form': form}
    return render(request, 'learning_log/edit_entry.html', context)

users/views.py
from django.shortcuts import render, reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect


# Create your views here.
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_log:index'))


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_log:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

templates/learning_log/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
 <head>
 <meta charset="utf-8">
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
 <meta name="viewport" content="width=device-width, initial-
scale=1">
 <title>Tiny Blog</title>
 {% bootstrap_css %}
 {% bootstrap_javascript %}
 </head>
 <body>
 <nav class="navbar navbar-default navbar-static-top">
 <div class="container">
 <div class="navbar-header">
 <button type="button" class="navbar-toggle collapsed"
 data-toggle="collapse" data-target="#navbar"
 aria-expanded="false" aria-controls="navbar">
 </button>
 <a class="navbar-brand" href="{% url 'learning_log:index'%}">
 Tiny Blog</a>
 </div>
 <div id="navbar" class="navbar-collapse collapse">
 <ul class="nav navbar-nav">
 <li><a href="{% url 'learning_log:topics' %}">#话题#</a></li>
 </ul>
 <ul class="nav navbar-nav navbar-right">
 {% if user.is_authenticated %}
 <li><a>你好呀， {{ user.username }}.</a></li>
 <li><a href="{% url 'users:logout' %}">登出</a></li>
 {% else %}
 <li><a href="{% url 'users:register' %}">注册</a>
</li>
 <li><a href="{% url 'users:login' %}">登录</a></li>
 {% endif %}
 </ul>
 </div>
 </div>
 </nav>
<div class="container">
 <div class="page-header">
 {% block header %}{% endblock header %}
 </div>
 <div>
 {% block content %}{% endblock content %}
 </div>
 </div>
 </body>
</html>

templates/learning_log/edit_entry.html
{% extends "learning_log/base.html" %}
{% block content %}
 <p><a href="{% url 'learning_log:topic' topic.id %}">{{ topic }}
</a></p>
 <p>编辑内容</p>
 <form action="{% url 'learning_log:edit_entry' entry.id %}"
method='post'>
 {% csrf_token %}
 {{ form.as_p }}
 <button name="Submit">保存更改</button>
 </form>
{% endblock content %}

templates/learning_log/index.html
{% extends "learning_log/base.html" %}
{% block header %}
 <div class='jumbotron'>
 <h1>随便写点什么吧</h1>
 </div>
{% endblock header %}
{% block content %}
 <h2>
 <a href="{% url 'users:register' %}">注册Tiny Blog账号</a> 赢取价值999RMB的精美大礼一份（嘻嘻）
 </h2>
 <h2>
 什么话题都可以啦，记得在里面写一点内容哦
 </h2><br><br><br>
    <h1 align="center"><a href="{% url 'learning_log:topics'%}">从 #话题# 开始</a></h1><br><br><br>
    <h6 align="right"><a href="/admin"> Mute-xD </a></h6>
{% endblock content %}

templates/learning_log/new_entry.html
{% extends "learning_log/base.html" %}
{% block content %}
 <p><a href="{% url 'learning_log:topic' topic.id %}">{{ topic }}
</a></p>
 <p>增加新内容</p>
 <form action="{% url 'learning_log:new_entry' topic.id %}"
method='post'>
 {% csrf_token %}
 {{ form.as_p }}
 <button name='Submit'>增加内容</button>
 </form>
{% endblock content %}

templates/learning_log/new_topic.html
{% extends "learning_log/base.html" %}
{% load bootstrap3 %}
{% block header %}
 <h2>增加一个新 #话题#</h2>
{% endblock header %}
{% block content %}
 <form action="{% url 'learning_log:new_topic' %}" method='post' class="form">
 {% csrf_token %}
 {% bootstrap_form form %}
 <p>由于此Blog结构为 #话题# -> 内容</p>
 <p>建议大家将 #话题# 设为公开，或使用根话题</p>
 {% buttons %}
 <button name="submit" class="btn btn-primary">增加话题</button>
 {% endbuttons %}
 </form>
{% endblock content %}

templates/learning_log/topic.html
{% extends 'learning_log/base.html' %}
{% block header %}
 <h2>{{ topic }}</h2>
{% endblock header %}
{% block content %}
 <p>
 <a href="{% url 'learning_log:new_entry' topic.id %}">增加新内容</a>
 </p>
 {% for entry in entries %}
 <div class="panel panel-default">
 <div class="panel-heading">
 <h3>
 {{ entry.createDate|date:'Y-m-d H:i' }}
 <small>
 <a href="{% url 'learning_log:edit_entry' entry.id %}">编辑</a>
 </small>
 </h3>
 </div>
 <div class="panel-body">
 {{ entry.text|linebreaks }}
 </div>
 </div> <!-- panel -->
 {% empty %}
 好冷清，一个内容也没有
 {% endfor %}
{% endblock content %}

templates/learning_log/topics.html
{% extends "learning_log/base.html" %}
{% block header %}
 <h1>#话题#</h1>
{% endblock header %}
{% block content %}
 <ul>
 {% for topic in topics %}
 <li>
 <h3>
 <a href="{% url 'learning_log:topic' topic.id %}">{{ topic}}</a>
 </h3>
 </li>
 {% empty %}
 <li>好冷清，一个话题也没有</li>
 {% endfor %}
 </ul>
 <h3><a href="{% url 'learning_log:new_topic' %}">增加话题</a></h3>
{% endblock content %}

templates/users/login.html
{% extends "learning_log/base.html" %}
{% load bootstrap3 %}
{% block header %}
 <h2>在这里登录你的账号</h2>
{% endblock header %}
{% block content %}
 <form method="post" action="{% url 'users:login' %}" class="form">
 {% csrf_token %}
 {% bootstrap_form form %}
 {% buttons %}
 <button name="submit" class="btn btn-primary">登录</button>
 {% endbuttons %}
 <input type="hidden" name="next" value="{% url 'learning_log:index' %}" />
 </form>
{% endblock content %}

templates/users/register.html
{% extends "learning_log/base.html" %}
{% block content %}
    <h4>十分感谢你的信任，虽然密码将自动加密，但出于安全考虑，以及作者能力水平，千 万 不 要 在这里填写与其他网站一样的密码。</h4>
 <form method="post" action="{% url 'users:register' %}">
 {% csrf_token %}
 {{ form.as_p }}
     <p>由于这里调用的是开源第三方库，密码有一些要求：1. 八位以上 2.不能纯数字 3.不要和用户名一模一样</p>
 <button name="submit">注册</button>
 <input type="hidden" name="next" value="{% url 'learning_log:index' %}" />
 </form>
{% endblock content %}